//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_test.EFProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        public int code { get; set; }
        public string model { get; set; }
        public short speed { get; set; }
        public short ram { get; set; }
        public float hd { get; set; }
        public string cd { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
